name: com.example.flutter_cubit_app
description: A simple Flutter app with a login screen and a home screen using the Cubit pattern for state management.
version: 1.0.0
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  bloc: ^8.0.1
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.1
  mocktail: ^0.2.0

flutter:
  uses-material-design: true